database:
      driverClass: org.h2.Driver
      user: sa
      password:
      url: jdbc:h2:tcp://localhost/server~/truecaller;TRACE_LEVEL_SYSTEM_OUT=3
      properties:
         charSet: UTF-8
         validationQuery: "/* MyService Health Check */ SELECT 1"
